### ISSUE TITLE
SVGs for icons

### ISSUE THREAD

**Issue by heykc** [heykc/READMEDungeon#29]
(list out all svg icons we need)

**Comment by heykc** [comment]
@KevinW90 can you go let me know all the icons we know we need right now?

**Comment by KevinW90** [comment]
/* icon name (current icon from Font Awesome)*/
player (user
move (arrows-alt)
inventory (boxes)
enemy (skull) //or a separate icon for different enemy type
chest (toolbox)
//empty slots//
empty left hand (null)
empty right hand (null)
empty head (null)
empty torso (null)
empty accessory (null)
//filled slots
left fist (null)
right fist (null)
one icon for each weapon type
helmet (null)
tunic/breastplate (null)
ring/amulet (null)

**Comment by heykc** [comment]
effects:
[  ] poison
[  ] healing
[  ] impervious
[  ] invisible
