### ISSUE TITLE
Finite State Machine

### ISSUE THREAD

**Issue by heykc** [heykc/READMEDungeon#43]
Build a state machine that objects can use to handle their own personal states. 

This should allow an object to move from a specific state to another state by calling a transition function. 

This should also allow the ability to define specific callbacks to specific stages of transitions to handle certain tasks during certain transitions.

**Comment by bmackley** [comment]
Hey @heykc have you thought about using Redux or Flux or another state management tool instead of rebuilding it yourself from the ground up?
